import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ToastContainer} from "react-toastify"
import "react-toastify/dist/ReactToastify.css";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Envy Car Sales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
